<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuickSeeder extends Seeder
{
    public function run(): void
    {
        // Portfolios
        DB::table('portfolios')->insert([
            [
                'title' => 'SantriGresik.me',
                'slug' => 'santrigresik-me',
                'category' => 'web',
                'description' => 'Website portfolio agency digital SantriGresik dengan desain modern dan animasi interaktif.',
                'image' => 'images/portfolio/santrigresik.jpg',
                'url' => 'https://santrigresik.me',
                'client_name' => 'SantriGresik',
                'year' => 2024,
                'technologies' => json_encode(['Laravel', 'Tailwind CSS', 'JavaScript']),
                'color' => '#10b981',
                'is_featured' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Anti Diet Club',
                'slug' => 'anti-diet-club',
                'category' => 'web',
                'description' => 'Website toko online cookies dengan sistem cart dan integrasi WhatsApp.',
                'image' => 'images/portfolio/antidietclub.jpg',
                'url' => 'https://santrigresik.me/antidietclub',
                'client_name' => 'Anti Diet Club',
                'year' => 2024,
                'technologies' => json_encode(['Laravel', 'Filament', 'Tailwind CSS']),
                'color' => '#f59e0b',
                'is_featured' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'An-Nibros',
                'slug' => 'an-nibros',
                'category' => 'app',
                'description' => 'Aplikasi digital ibadah dengan fitur al-Quran, wirid, ratib, dan doa pilihan.',
                'image' => 'images/portfolio/annibros.jpg',
                'url' => '#',
                'client_name' => 'PP Nurul Huda',
                'year' => 2024,
                'technologies' => json_encode(['Flutter', 'Laravel', 'Firebase']),
                'color' => '#3b82f6',
                'is_featured' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sistem Absensi PP Al Ibrohimi',
                'slug' => 'sistem-absensi-al-ibrohimi',
                'category' => 'system',
                'description' => 'Sistem absensi guru dengan GPS tracking dan verifikasi wajah.',
                'image' => 'images/portfolio/absensi.jpg',
                'url' => 'https://presensi.alibrohimi.my.id',
                'client_name' => 'PP Al Ibrohimi',
                'year' => 2023,
                'technologies' => json_encode(['Laravel', 'Filament', 'GPS API']),
                'color' => '#8b5cf6',
                'is_featured' => false,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sidogiri Penerbit',
                'slug' => 'sidogiri-penerbit',
                'category' => 'web',
                'description' => 'Website penerbit buku dengan sistem katalog dan toko online.',
                'image' => 'images/portfolio/sidogiri-penerbit.jpg',
                'url' => 'https://sidogiripenerbit.com',
                'client_name' => 'Sidogiri Penerbit',
                'year' => 2023,
                'technologies' => json_encode(['Laravel', 'WooCommerce', 'WordPress']),
                'color' => '#ef4444',
                'is_featured' => false,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dialog Masa',
                'slug' => 'dialog-masa',
                'category' => 'web',
                'description' => 'Redesign website dengan modern UI dan improved UX.',
                'image' => 'images/portfolio/dialogmasa.jpg',
                'url' => 'https://dialogmasa.com',
                'client_name' => 'Dialog Masa',
                'year' => 2023,
                'technologies' => json_encode(['Laravel', 'Tailwind CSS']),
                'color' => '#06b6d4',
                'is_featured' => false,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Products
        DB::table('products')->insert([
            [
                'name' => 'Mebel Custom',
                'slug' => 'mebel-custom',
                'category' => 'Mebel',
                'description' => 'Pembuatan mebel custom dengan desain modern dan bahan berkualitas.',
                'image' => 'images/products/mebel.jpg',
                'price' => 'Hubungi Kami',
                'price_note' => 'Harga tergantung desain dan ukuran',
                'color' => '#10b981',
                'is_available' => true,
                'is_featured' => true,
                'whatsapp_message' => 'Halo, saya tertarik dengan Mebel Custom. Mohon infonya.',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gazebo Minimalis',
                'slug' => 'gazebo-minimalis',
                'category' => 'Gazebo',
                'description' => 'Gazebo minimalis untuk taman atau halaman rumah dengan berbagai pilihan ukuran.',
                'image' => 'images/products/gazebo.jpg',
                'price' => 'Mulai Rp 5.000.000',
                'price_note' => 'Tergantung ukuran dan bahan',
                'color' => '#f59e0b',
                'is_available' => true,
                'is_featured' => true,
                'whatsapp_message' => 'Halo, saya tertarik dengan Gazebo Minimalis. Mohon infonya.',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mimbar Masjid',
                'slug' => 'mimbar-masjid',
                'category' => 'Mimbar',
                'description' => 'Mimbar masjid ukir jepara dengan kualitas terbaik dan desain elegan.',
                'image' => 'images/products/mimbar.jpg',
                'price' => 'Mulai Rp 8.000.000',
                'price_note' => 'Tergantung ukuran dan ukiran',
                'color' => '#3b82f6',
                'is_available' => true,
                'is_featured' => true,
                'whatsapp_message' => 'Halo, saya tertarik dengan Mimbar Masjid. Mohon infonya.',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CNC Custom',
                'slug' => 'cnc-custom',
                'category' => 'CNC',
                'description' => 'Jasa cutting dan engraving CNC untuk berbagai bahan (kayu, akrilik, dll).',
                'image' => 'images/products/cnc.jpg',
                'price' => 'Mulai Rp 50.000',
                'price_note' => 'Tergantung ukuran dan kerumitan',
                'color' => '#8b5cf6',
                'is_available' => true,
                'is_featured' => true,
                'whatsapp_message' => 'Halo, saya tertarik dengan jasa CNC Custom. Mohon infonya.',
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kavlingan Asnawi',
                'slug' => 'kavlingan-asnawi',
                'category' => 'Kavlingan',
                'description' => 'Kavling siap bangun dengan lokasi strategis dan fasilitas lengkap.',
                'image' => 'images/products/kavlingan.jpg',
                'price' => 'Hubungi Kami',
                'price_note' => 'Tergantung lokasi dan luas',
                'color' => '#ef4444',
                'is_available' => true,
                'is_featured' => true,
                'whatsapp_message' => 'Halo, saya tertarik dengan Kavlingan Asnawi. Mohon infonya.',
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Stats
        DB::table('stats')->insert([
            ['label' => 'Proyek Selesai', 'value' => 50, 'icon' => 'check-circle', 'sort_order' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['label' => 'Klien Puas', 'value' => 30, 'icon' => 'smile', 'sort_order' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['label' => 'Tahun Pengalaman', 'value' => 5, 'icon' => 'award', 'sort_order' => 3, 'created_at' => now(), 'updated_at' => now()],
        ]);

        $this->command->info('Quick seeding completed successfully!');
    }
}